/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "nfs.h"
#include "../enfsprot.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };
BOOL g_isNetOk = TRUE;
extern void AddDisconnectCount();

void set_timeout(int timeout)
{
	TIMEOUT.tv_sec = timeout;
}

bool_t
nfsproc3_null_3(void *argp, CLIENT *clnt,char *pResult)
{
	memset((char *)pResult, 0, sizeof(char));
	if (clnt_call (clnt, NFSPROC3_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) pResult,
		TIMEOUT) != RPC_SUCCESS) {
		return FALSE;
	}
	return TRUE;
}

bool_t
enfsproc_getblksargs(CLIENT *clnt, 
                     nfs3_getblksargs *argp, 
                     nfs3_bcache * pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFS3PROC_GETBLKS,
			(xdrproc_t) xdr_getblksargs, (caddr_t) argp,
			(xdrproc_t) xdr_bcache, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) 
		{
			AddDisconnectCount();
			return FALSE;
		}
		
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_getattr_3(GETATTR3args *argp, CLIENT *clnt, GETATTR3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_GETATTR,
			(xdrproc_t) xdr_GETATTR3args, (caddr_t) argp,
			(xdrproc_t) xdr_GETATTR3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_setattr_3(SETATTR3args *argp, CLIENT *clnt, SETATTR3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_SETATTR,
			(xdrproc_t) xdr_SETATTR3args, (caddr_t) argp,
			(xdrproc_t) xdr_SETATTR3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_lookup_3(LOOKUP3args *argp, CLIENT *clnt, LOOKUP3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_LOOKUP,
			(xdrproc_t) xdr_LOOKUP3args, (caddr_t) argp,
			(xdrproc_t) xdr_LOOKUP3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_access_3(ACCESS3args *argp, CLIENT *clnt, ACCESS3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_ACCESS,
			(xdrproc_t) xdr_ACCESS3args, (caddr_t) argp,
			(xdrproc_t) xdr_ACCESS3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_readlink_3(READLINK3args *argp, CLIENT *clnt, READLINK3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_READLINK,
			(xdrproc_t) xdr_READLINK3args, (caddr_t) argp,
			(xdrproc_t) xdr_READLINK3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_read_3(READ3args *argp, CLIENT *clnt, READ3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_READ,
			(xdrproc_t) xdr_READ3args, (caddr_t) argp,
			(xdrproc_t) xdr_READ3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_write_3(WRITE3args *argp, CLIENT *clnt, WRITE3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_WRITE,
			(xdrproc_t) xdr_WRITE3args, (caddr_t) argp,
			(xdrproc_t) xdr_WRITE3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_create_3(CREATE3args *argp, CLIENT *clnt, CREATE3res *pResult)
{
	if( g_isNetOk )
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_CREATE,
			(xdrproc_t) xdr_CREATE3args, (caddr_t) argp,
			(xdrproc_t) xdr_CREATE3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_mkdir_3(MKDIR3args *argp, CLIENT *clnt, MKDIR3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_MKDIR,
			(xdrproc_t) xdr_MKDIR3args, (caddr_t) argp,
			(xdrproc_t) xdr_MKDIR3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_symlink_3(SYMLINK3args *argp, CLIENT *clnt, SYMLINK3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_SYMLINK,
			(xdrproc_t) xdr_SYMLINK3args, (caddr_t) argp,
			(xdrproc_t) xdr_SYMLINK3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;
		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_mknod_3(MKNOD3args *argp, CLIENT *clnt, MKNOD3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_MKNOD,
			(xdrproc_t) xdr_MKNOD3args, (caddr_t) argp,
			(xdrproc_t) xdr_MKNOD3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_remove_3(REMOVE3args *argp, CLIENT *clnt, REMOVE3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_REMOVE,
			(xdrproc_t) xdr_REMOVE3args, (caddr_t) argp,
			(xdrproc_t) xdr_REMOVE3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}

}

bool_t
nfsproc3_rmdir_3(RMDIR3args *argp, CLIENT *clnt, RMDIR3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_RMDIR,
			(xdrproc_t) xdr_RMDIR3args, (caddr_t) argp,
			(xdrproc_t) xdr_RMDIR3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_rename_3(RENAME3args *argp, CLIENT *clnt, RENAME3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_RENAME,
			(xdrproc_t) xdr_RENAME3args, (caddr_t) argp,
			(xdrproc_t) xdr_RENAME3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_link_3(LINK3args *argp, CLIENT *clnt, LINK3res *pResult)
{
	if ( g_isNetOk )
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_LINK,
			(xdrproc_t) xdr_LINK3args, (caddr_t) argp,
			(xdrproc_t) xdr_LINK3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_readdir_3(READDIR3args *argp, CLIENT *clnt, READDIR3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_READDIR,
			(xdrproc_t) xdr_READDIR3args, (caddr_t) argp,
			(xdrproc_t) xdr_READDIR3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_readdirplus_3(READDIRPLUS3args *argp, CLIENT *clnt, READDIRPLUS3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_READDIRPLUS,
			(xdrproc_t) xdr_READDIRPLUS3args, (caddr_t) argp,
			(xdrproc_t) xdr_READDIRPLUS3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_fsstat_3(FSSTAT3args *argp, CLIENT *clnt, FSSTAT3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_FSSTAT,
			(xdrproc_t) xdr_FSSTAT3args, (caddr_t) argp,
			(xdrproc_t) xdr_FSSTAT3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_fsinfo_3(FSINFO3args *argp, CLIENT *clnt,FSINFO3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_FSINFO,
			(xdrproc_t) xdr_FSINFO3args, (caddr_t) argp,
			(xdrproc_t) xdr_FSINFO3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_pathconf_3(PATHCONF3args *argp, CLIENT *clnt,PATHCONF3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_PATHCONF,
			(xdrproc_t) xdr_PATHCONF3args, (caddr_t) argp,
			(xdrproc_t) xdr_PATHCONF3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}

bool_t
nfsproc3_commit_3(COMMIT3args *argp, CLIENT *clnt,COMMIT3res *pResult)
{
	if ( g_isNetOk ) 
	{
		memset((char *)pResult, 0, sizeof(*pResult));
		if (clnt_call (clnt, NFSPROC3_COMMIT,
			(xdrproc_t) xdr_COMMIT3args, (caddr_t) argp,
			(xdrproc_t) xdr_COMMIT3res, (caddr_t) pResult,
			TIMEOUT) != RPC_SUCCESS) {
			AddDisconnectCount();
			return FALSE;
		}
		return TRUE;		
	}
	else
	{
		return FALSE;
	}
}










































